juxt/tick

project.clj
src/tick/cal.clj
src/tick/core.clj
src/tick/timeline.clj

Clojure 1.9.0a16 removed the `clojure.spec` namespace, moving it to a separate lib, under the `clojure.spec.alpha` namespace. This PR adds the spec.alpha lib as a dependency, and updates the namespace references.

Replacing clojure.spec with clojure.spec.alpha

---

src/tick/timeline.clj

Replacing `ZonedDateTime` and `Duration` with their super-interfaces `Temporal` and `TemporalAmount` allows callers to pass other concrete types to `periodic-seq` - e.g. passing a `Period` rather than a `Duration`.
(This probably applies to the `(s/def :tick/date ...)` too?)

Unnecessarily specific type annotations on `periodic-seq`

---

README.adoc

Some code blocks did not have their vars imported properly.
I might even suggest to use fully qualified names in all snippets but not too concerned about the first one as it has proper imports in contrast to the rest.

dont use referred vars as much in readme

---

src/tick/core.cljc
test/tick/alpha/api/dates_test.cljc

Use `(current-zone)` in core instead of calling
`(cljc.java-time.zone-id/system-default)` directly
Previously creating a clock from an instant, and converting an date-time to a zoned- or offset-date-time did not use the current clock.
Issue #49

Respect clock in date time inst conversion

---

src/tick/interval.cljc
test/tick/interval_test.cljc

resolves #58 
This is the minimal fix for this issue, and I got some tests working.
I think it may additionally be worth adding a precondition to check that the collection argument satisfies `ordered-disjoint-intervals?` (`group-by-intervals` does this). 
Alternatively, and I'm less confident this is a good idea, `tick.interval/unite` could be called on the collection argument prior to handling it, so that overlapping intervals in a collection could also be valid.

complement should work for meeting intervals

---

src/tick/core.cljc
test/tick/alpha/api_test.cljc

Due to subtle differences in regex API in the JVM vs JS runtime, some constructors were broken.
In Clojurescript
```cljs
(re-matches #"(tue)(s|sday)?" "tuesday")
=> nil
(re-matches #"^(tue)(s|sday)?$" "tuesday")
=> ["tuesday" "tue" "sday"]
```
Wheras in Clojure
```clj
(re-matches #"(tue)(s|sday)?" "tuesday")
=> ["tuesday" "tue" "sday"]
(re-matches #"^(tue)(s|sday)?$" "tuesday")
=> ["tuesday" "tue" "sday"]
```
This means we can't use `(t/day-of-week "TUESDAY")` in Clojurescript. The additional prefix/suffix isn't necessary for all the days/months but I thought it better to be consistent.
Also thanks a lot for putting this library together and open-sourcing it. It's very well written and easy to read. I'm getting a ton of mileage out of it!

Kt day constructor fixes

---

src/tick/core.cljc
test/tick/alpha/api_test.cljc

Pull request implements `ITimeComparison` as discussed in #74  and adds implementation for IBetween.

Implement ITimeComparison and IBetween for #inst

---

src/tick/interval.cljc

:during case for instance/difference was ignoring end of Y
Fixes #76

Doesn't remove ys head in case :during

---

src/tick/core.cljc

Fix bug where zoned-date-time strings are mistakenly identified as instants, causing the parse function to throw.
Specifically, the string "2020-03-06T01:02:04.637Z[Europe/London]" is identified as an instant when in fact it is not a valid instant, but a valid zoned-date-time. Instants cannot have a time zone so I have updated the regex to reflect this.
To reproduce the bug:
`(t/parse (str (t/zoned-date-time #inst "2019")))`
Should return `#time/zoned-date-time "2019-01-01T00:00Z[Europe/London]"`
Instead it returns
```
Execution error (DateTimeParseException) at java.time.format.DateTimeFormatter/parseResolved0 (DateTimeFormatter.java:2049).
Text '2019-01-01T00:00Z[Europe/London]' could not be parsed, unparsed text found at index 16
```

Fix bug in parse function

---

src/tick/core.cljc
src/tick/deprecated/cal.clj

TemporalAmount as the step param instead of using a Long and only
being incrementable by days. This matches the behavior of the other
functions.
In response to my own discovery of Issue #84 which was submitted by someone else.
https://github.com/juxt/tick/issues/84

Use Period for step increment for LocalDate (range) calls.

---

src/tick/alpha/api.cljc
src/tick/core.cljc
test/tick/alpha/api_test.cljc

I added a test for the constructor. I don't know if that is sufficient. I'm happy to make the necessary changes.

Add new-year-month to core, api

---

docs/cookbook/misc.adoc
docs/cookbook/reference.adoc

The eval only seems to evaluate the last sexp in the block, so swapped out the `def`s for `let`s

Update docs so examples work

---

src/tick/core.cljc

Hi there,
I have been using Tick in my project for some time, but when I recently migrated from a JavaScript/NodeJS runtime to a Java/GraalVM runtime, I found that various type hints were needed in order for the GraalVM `native-image` command to build working executables.
Thanks 🙂

Various type hints for GraalVM native image

---

.circleci/config.yml
.dir-locals.el
.gitignore
Makefile
README.adoc
bin/kaocha
deps.edn
test/tick/alpha/api_test.cljc
test/tick/interval_test.cljc
tests.edn

Change a few things in the way tests are run:
- use Kaocha to run clojure tests
-  rewrite the circleci configuration to use 3 different jobs
-  add a missing `is` that was discovered when running kaocha
Clojurescript tests should also be ported but it's not so easy unfortunately, so should be done in another PR later on.

Use Kaocha to run tests

---

src/tick/alpha/ical.clj

No difference most of the time, but matters in the last week of the year - was rendering `2021-12-31` as `20221231` :)

Using `yyyy` (year-of-era) rather than `YYYY` (week-based-year) in ical formatters

---

src/tick/core.cljc
test/tick/api_test.cljc

Fixes #161
Added `day-of-week` protocol to `DayOfWeek` so that the various adjusters work (`t/next`, `t/next-or-same`...).
Tests included.

Fix error when using adjusters that make use of day-of-week

---

src/tick/core.cljc
test/tick/api_test.cljc

A missing call to `neg?` means that `<=` for durations return -1 or 1 (or `true` when the values are equal), i.e., the return value is always truthy.

Comparison for duration returns ints instead of bools

---

src/tick/alpha/ical.clj
test/tick/alpha/ical_test.clj

This issue showed up when parsing `REFRESH-INTERVAL;VALUE=DURATION:PT48H` from ical files.
Previously would fail with `\- - failed: #{\:} in: [7] at: [:colon] spec: :user/contentline`

Fix issue with parsing iana tokens with hyphens

---

docs/cookbook/reference.adoc

Fixes weird formatting, see img for current behaviour.

Fix formatting error in reference

---

src/tick/alpha/interval.cljc
test/tick/alpha/interval_test.cljc

The tests for interval/concur had no case with three or more arguments. Therefore the case where two adjecent intervals returns nil that is sent to (relation x y) in the next iteration was missed.

Make interval/concur handle three or more adjecent intervals

---

src/tick/core.cljc

Change example format symbols to less surprising choices as per java.time.format.DateTimeFormatter

Adjust core/formatter docstring

---

src/tick/alpha/ical.clj
test/tick/alpha/ical_test.clj

Hi, I'm trying to parse an ics file that contains long lines split by so called "line folding technique".
According to https://www.ietf.org/rfc/rfc2445.txt
Lines of text SHOULD NOT be longer than 75 octets, excluding the line
break. Long content lines SHOULD be split into a multiple line
representations using a line "folding" technique. That is, a long
line can be split between any two characters by inserting a CRLF
immediately followed by a single linear white space character (i.e.,
SPACE, US-ASCII decimal 32 or HTAB, US-ASCII decimal 9). Any sequence
of CRLF followed immediately by a single linear white space character
is ignored (i.e., removed) when processing the content type.
Unfortunately, while `unfolding-line-seq*`concatenates such lines properly, it doesn't skip the leading …

ical.clj. Fix multiline folding according to rfc2445
